export const Languages = {
  selection: 'en',
  en: {
    deino: 'voice-deino-sound-en',
    deinocheirus: 'voice-deinocheirus-sound-en',
    dimetrodon: 'voice-dimetrodon-sound-en',
    edmon: 'voice-edmon-sound-en',
    gate1: 'voice-gate1-sound-en',
    gate2: 'voice-gate2-sound-en',
    gate3: 'voice-gate3-sound-en',
    gate4: 'voice-gate4-sound-en',
    gate5: 'voice-gate5-sound-en',
    lagoon1: 'voice-lagoon1-sound-en',
    ptera: 'voice-ptera-sound-en',
    quetza: 'voice-quetza-sound-en',
    raptor: 'voice-raptor-sound-en',
    sarco: 'voice-sarco-sound-en',
    spino: 'voice-spino-sound-en',
    trex: 'voice-trex-sound-en',
  },
  fr: {
    aviary1: 'voice-aviary1-sound-fr',
    deino: 'voice-deino-sound-fr',
    deinocheirus: 'voice-deinocheirus-sound-fr',
    dimetrodon: 'voice-dimetrodon-sound-fr',
    edmon: 'voice-edmon-sound-fr',
    gate1: 'voice-gate1-sound-fr',
    gate2: 'voice-gate2-sound-fr',
    gate3: 'voice-gate3-sound-fr',
    gate4: 'voice-gate4-sound-fr',
    gate5: 'voice-gate5-sound-fr',
    lagoon1: 'voice-lagoon1-sound-fr',
    ptera: 'voice-ptera-sound-fr',
    quetza: 'voice-quetza-sound-fr',
    raptor: 'voice-raptor-sound-fr',
    sarco: 'voice-sarco-sound-fr',
    spino: 'voice-spino-sound-fr',
    trex: 'voice-trex-sound-fr',
  },
};
