export const Languages = {
  selection: 'en',
  en: {
    aviary1: 'voice-aviary1-sound-en',
    deino: 'voice-deino-sound-en',
    dimetrodon: 'voice-dimetrodon-sound-en',
    dilo: 'voice-dilo-sound-en',
    cinema1: 'voice-cinema1-sound-en',
    gate1: 'voice-gate1-sound-en',
    gate2: 'voice-gate2-sound-en',
    gate3: 'voice-gate3-sound-en',
    gate4: 'voice-gate4-sound-en',
    lagoon1: 'voice-lagoon1-sound-en',
    quetza: 'voice-quetza-sound-en',
    raptor: 'voice-raptor-sound-en',
    trex1: 'voice-trex1-sound-en',
    trex2: 'voice-trex2-sound-en',
    trice1: 'voice-trice1-sound-en',
    trice2: 'voice-trice2-sound-en',
  },
  fr: {
    aviary1: 'voice-aviary1-sound-fr',
    deino: 'voice-deino-sound-fr',
    dimetrodon: 'voice-dimetrodon-sound-fr',
    dilo: 'voice-dilo-sound-fr',
    cinema1: 'voice-cinema1-sound-fr',
    gate1: 'voice-gate1-sound-fr',
    gate2: 'voice-gate2-sound-fr',
    gate3: 'voice-gate3-sound-fr',
    gate4: 'voice-gate4-sound-fr',
    lagoon1: 'voice-lagoon1-sound-fr',
    quetza: 'voice-quetza-sound-fr',
    raptor: 'voice-raptor-sound-fr',
    trex1: 'voice-trex1-sound-fr',
    trex2: 'voice-trex2-sound-fr',
    trice1: 'voice-trice1-sound-fr',
    trice2: 'voice-trice2-sound-fr',
  },
};
